services:

  mongodb:
    image: mongo:7.0
    container_name: fraudsentinel-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-fraudadmin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS:-fraudadmin123}
      MONGO_INITDB_DATABASE: fraudsentinel
    ports:
      - "27017:27017"
    volumes:
      - fraudsentinel-mongo-data:/data/db
    networks:
      - fraudsentinel-net
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  backend:
    build: .
    container_name: fraudsentinel-api
    restart: unless-stopped
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://${MONGO_USER:-fraudadmin}:${MONGO_PASS:-fraudadmin123}@mongodb:27017/fraudsentinel?authSource=admin
      SECURITY_JWT_SECRET: ${SECURITY_JWT_SECRET:-Y2ktdGVzdC1zZWNyZXQta2V5LWZvci1qd3QtbXVzdC1iZS1sb25nLWVub3VnaA==}
      APP_COOKIE_SECURE: ${APP_COOKIE_SECURE:-false}
      APP_STORAGE_ROOT: /home/fraudsentinel/uploads
      SPRING_PROFILES_ACTIVE: dev
      APP_SEED_ADMIN_PASSWORD: ${APP_SEED_ADMIN_PASSWORD:-ChangeMeAdmin123!}
      APP_SEED_ANALYST_PASSWORD: ${APP_SEED_ANALYST_PASSWORD:-ChangeMeAnalyst123!}
      APP_SEED_COMPLIANCE_PASSWORD: ${APP_SEED_COMPLIANCE_PASSWORD:-ChangeMeCompliance123!}
      APP_SEED_CLIENT_PASSWORD: ${APP_SEED_CLIENT_PASSWORD:-ChangeMeClient123!}
    ports:
      - "8080:8080"
    volumes:
      - fraudsentinel-uploads:/home/fraudsentinel/uploads
    networks:
      - fraudsentinel-net

volumes:
  fraudsentinel-mongo-data:
  fraudsentinel-uploads:

networks:
  fraudsentinel-net:
    driver: bridge
