spring.application.name=FraudSentinel
spring.data.mongodb.uri=mongodb+srv://jessborgesb_db_user:FraudSentinel2026@fraudsentinel.tlt3s9y.mongodb.net/fraudsentinel?appName=FraudSentinel
spring.data.mongodb.database=fraudsentinel
server.port=8081